import PostgresTable from '../../lib/schema/PostgresTable';
import Elegant from '../../src/Elegant';

describe('PostgresTable', () => {
  let table:PostgresTable;
  let db:Elegant;

  beforeEach(async () => {
    db = await Elegant.connection('postgres')
    table = new PostgresTable('users', 'create', db)
  })

  describe('boolean', () => {
    it('boolean', () => {
      table.boolean('is_active')
      const sql = table.toStatement()
      const expected = 'CREATE TABLE "users" (\n  "is_active" BOOLEAN\n)'
      expect(sql).toEqual(expected)
    })
    it('boolean with default value', () => {
      table.boolean('is_active', true)
      const sql = table.toStatement()
      const expected = 'CREATE TABLE "users" (\n  "is_active" BOOLEAN DEFAULT true\n)'
      expect(sql).toEqual(expected)
    })
  })

  describe('modifiers', () => {
    it('autoIncrement', () => {
      table.integer('id', 255).autoIncrement().primary()
      const sql = table.toStatement()
      const expected = 'CREATE TABLE "users" (\n  "id" INT(255) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY\n)'
      expect(sql).toEqual(expected)
    })
  })

});
