services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: elegant
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - elegant-postgres:/var/lib/postgresql/data
    restart: always
  mariadb:
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: password
      MYSQL_DATABASE: elegant
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    ports:
      - "3308:3306"
    volumes:
      - elegant-mariadb:/var/lib/mysql
    restart: always
  mysql:
    image: mysql:8.4
    container_name: elegant-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password # Replace with a strong password
      MYSQL_DATABASE: elegant    # Optional: Initial database to create
      MYSQL_USER: elegant                 # Optional: Initial user to create
      MYSQL_PASSWORD: password    # Optional: Password for the initial user
    ports:
      - "3333:3306"
    volumes:
      - elegant-mysql:/var/lib/mysql # Named volume for persistent data
    restart: always

volumes:
  elegant-mysql: # Define the named volume
    name: elegant-mysql
  elegant-mariadb:
    name: elegant-mariadb
  elegant-postgres:
    name: elegant-postgres
